# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            dimroc
tagline:          'The Development Blog of Dimitri Roche'
description:      'The Development Blog of Dimitri Roche'
url:              http://www.dimroc.com
baseurl:          /

author:
  name:           'Dimitri Roche'
  twitter:        https://twitter.com/dimroc
  github:         https://github.com/dimroc
  experiments:    http://experiments.dimroc.com

paginate:         10
excerpt_separator: <!--more-->

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dimroc/dimroc.github.io
