# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            dimroc
tagline:          'blog'
description:      'The Development Blog of Dimitri Roche'
url:              http://www.dimroc.com
baseurl:          /

author:
  name:           'Dimitri Roche'
  twitter:        https://twitter.com/dimroc
  github:         https://github.com/dimroc
  experiments:    http://experiments.dimroc.com

paginate:         100
excerpt_separator: <!--more-->

# Tags
tag_page_layout: tag_page
tag_page_dir: tag

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dimroc/dimroc.github.io
