# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            dimroc
tagline:          'The development blog of Dimitri Roche'
description:      'The coding adventures of Dimitri Roche'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Dimitri Roche'
  url:            https://twitter.com/dimroc

paginate:         10
excerpt_separator: <!--more-->

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dimroc
